### ISSUE TITLE
Can't run it?

### ISSUE THREAD

**Issue by CYCOABHI** [TachyonRSA/PoGoTos#2]
My accounts.txt is like this:-

asdas:saad
asd:asdasd
Asad:asdasd
asdasd:sadasd
xxx:xxx
asdasd:asdasd

etc etc.

I'm running a command window in the folder of PoGoTos and writing this:- "tos.py accounts.txt"

I keep getting this error:-

Traceback (most recent call last):
  File "C:\Users\XXXX\Downloads\Pokemon Go Shit\PoGoTos-master\tos.py", line 6, in <module>
    from pgoapi import PGoApi
ImportError: No module named pgoapi

C:\Users\XXXX\Downloads\Pokemon Go Shit\PoGoTos-master>

**Comment by TachyonRSA** [comment]
#8438272 - Please have a look at latest commit, you will need pip installed and then use: pip install -r requirements.txt

**Comment by CYCOABHI** [comment]
Collecting pgoapi from git+https://github.com/keyphact/pgoapi.git#egg=pgoapi (from -r requirements.txt (line 18))
  Cloning https://github.com/keyphact/pgoapi.git to c:\users\abhirup\appdata\local\temp\pip-build-zzrrvd\pgoapi
  Error [Error 2] The system cannot find the file specified while executing command git clone -q https://github.com/keyphact/pgoapi.git c:\users\abhirup\appdata\local\temp\pip-build-zzrrvd\pgoapi
Cannot find command 'git'
